export const CHECKED = 'September 19, 2026';

export const PLACES = [
  {
    id: 'pitt',
    name: 'Pitt Pantry',
    group: 'campus',
    lat: 40.44477,
    lng: -79.95725,
    precision: 'address',
    schedule: { 1: [[11, 14]], 2: [[11, 19]], 3: [[11, 19]] },
    who: 'Pitt students, faculty and staff',
    address: "O'Hara Student Center, 4024 O'Hara Street, Pittsburgh, PA 15213",
    hours: ['Fall hours: Monday 11 a.m. to 2 p.m.', 'Tuesday and Wednesday 11 a.m. to 7 p.m.', 'Closed on university holidays and breaks'],
    notes: 'Walk-ins welcome, no appointment. Bring a valid Pitt ID. Up to two visits a month, and you can bring one other person.',
    contact: { label: 'pantry@pitt.edu', href: 'mailto:pantry@pitt.edu' },
    source: { label: 'Pitt Student Affairs', href: 'https://www.studentaffairs.pitt.edu/care-and-resources/pitt-pantry' },
    confirmed: true,
  },
  {
    id: 'cmu',
    name: 'CMU Pantry',
    group: 'campus',
    lat: 40.44687,
    lng: -79.94677,
    precision: 'address',
    who: 'Carnegie Mellon students (no need to prove need)',
    address: 'Residence on Fifth, 4700 Fifth Avenue, First Floor, Pittsburgh, PA 15213',
    hours: ['Open in blocks most days except Sunday', 'Book a time through the Pantry Shopping Form in TartanConnect'],
    notes: 'Reported: one shopping visit a week. Check the FAQ for the current rules.',
    contact: { label: 'cmu-pantry@andrew.cmu.edu', href: 'mailto:cmu-pantry@andrew.cmu.edu' },
    source: { label: 'CMU Student Affairs FAQ', href: 'https://www.cmu.edu/student-affairs/resources/cmu-pantry/faqs.html' },
    confirmed: false,
  },
  {
    id: 'duquesne',
    name: 'McAnulty Keating Pantry (Duquesne)',
    group: 'campus',
    lat: 40.43653,
    lng: -79.99048,
    precision: 'area',
    who: 'Duquesne students, faculty and staff',
    address: 'College Hall, Rooms 347 to 350, Duquesne University, Pittsburgh, PA',
    hours: ['Reported: 8 a.m. to 6 p.m. on weekdays', 'Check the source for the current schedule'],
    notes: 'No application, no limits and no questions asked, according to Duquesne. Private access outside regular hours is available through the Migration Club.',
    contact: { label: 'migrationclub@duq.edu', href: 'mailto:migrationclub@duq.edu' },
    source: { label: 'Duquesne University', href: 'https://www.duq.edu/research/centers-and-institutes/center-for-migration-displacement-and-community-studies/the-pantry.php' },
    confirmed: false,
  },
  {
    id: 'pointpark',
    name: 'Pioneer Pantry and Corner Store (Point Park)',
    group: 'campus',
    lat: 40.43865,
    lng: -80.00177,
    precision: 'area',
    who: 'Point Park students',
    address: 'Thayer Hall, first floor, Point Park University, Pittsburgh, PA',
    hours: ['Hours change every semester. Check the source for this term.'],
    notes: 'Students can order online for pickup, and orders are identified only by student ID number.',
    contact: null,
    source: { label: 'Point Park University news', href: 'https://www.pointpark.edu/news/pioneer-pantry-serves-point-park-students-in-need' },
    confirmed: false,
  },
  {
    id: 'chs',
    name: 'CHS Oakland Food Pantry',
    group: 'oakland',
    lat: 40.43363,
    lng: -79.96144,
    precision: 'address',
    schedule: { 3: [[11, 18]], 4: [[15, 18]] },
    who: 'Community food pantry. Ask about any ID or sign-up when you call.',
    address: '370 Lawn Street, Pittsburgh, PA 15213',
    hours: ['Wednesday 11 a.m. to 6 p.m.', 'Thursday 3 p.m. to 6 p.m.'],
    notes: 'Another listing shows different hours, so call before you go.',
    contact: { label: '(412) 246-1688', href: 'tel:+14122461688' },
    source: { label: 'Greater Pittsburgh Community Food Bank', href: 'https://pittsburghfoodbank.org/resources/chs-oakland-food-pantry/' },
    confirmed: false,
  },
  {
    id: 'pcsi',
    name: 'PCSI Food Pantry',
    group: 'oakland',
    lat: 40.45124,
    lng: -79.952,
    precision: 'address',
    schedule: { 1: [[10, 16]], 2: [[10, 16]], 3: [[10, 16]], 4: [[10, 20]], 5: [[10, 16]] },
    who: 'Households that meet income guidelines and live in Pittsburgh',
    address: '249 N. Craig Street, Pittsburgh, PA 15213',
    hours: ['Monday, Tuesday, Wednesday and Friday 10 a.m. to 4 p.m.', 'Thursday 10 a.m. to 8 p.m.'],
    notes: 'Heads up: first visits and new years need a photo ID, proof of income for everyone in your household, and proof of Pittsburgh residency. That may not fit every student, so call first. One visit a month.',
    contact: { label: '412-904-4700', href: 'tel:+14129044700' },
    source: { label: 'Pittsburgh Community Services', href: 'https://pghcsi.org/services/food-pantry-nutrition-support/' },
    confirmed: true,
  },
  {
    id: 'autonomous',
    name: 'Autonomous food distribution (Schenley Plaza)',
    group: 'oakland',
    lat: 40.44272,
    lng: -79.95256,
    precision: 'address',
    who: 'Open to the public',
    address: 'Schenley Plaza, Oakland, Pittsburgh, PA',
    hours: ['Listed as Thursdays and Fridays, 10 a.m. to noon'],
    notes: 'From a local list with no update date, so confirm it is still running.',
    contact: null,
    source: { label: 'Pitt, Pittsburgh-area food distributions', href: 'https://www.cec.pitt.edu/news/pittsburgh-area-food-drives-and-distributions' },
    confirmed: false,
  },
  {
    id: 'schenley',
    name: 'Food Bank distribution at Schenley Plaza',
    group: 'oakland',
    lat: 40.44272,
    lng: -79.95256,
    precision: 'address',
    who: 'Open to the public',
    address: 'Schenley Plaza, Oakland, Pittsburgh, PA',
    hours: ['Reported: first Wednesday of each month, 3:30 p.m. to 5:30 p.m.'],
    notes: 'Fresh produce and frozen meat, reported. Confirm the date on the Food Bank site before you go.',
    contact: null,
    source: { label: 'Greater Pittsburgh Community Food Bank', href: 'https://pittsburghfoodbank.org' },
    confirmed: false,
  },
  {
    id: 'bloomfield',
    name: 'Catholic Community of Bloomfield Food Pantry',
    group: 'nearby',
    lat: 40.46182,
    lng: -79.94513,
    precision: 'area',
    who: 'Open to the public, no requirements listed',
    address: '4921 Mend Way, Pittsburgh, PA 15224',
    hours: ['Listed as the third Saturday of every month, 7 a.m. to 10 a.m.'],
    notes: 'From a local list with no update date, so confirm before you go.',
    contact: null,
    source: { label: 'Pitt, Pittsburgh-area food distributions', href: 'https://www.cec.pitt.edu/news/pittsburgh-area-food-drives-and-distributions' },
    confirmed: false,
  },
  {
    id: 'fnb',
    name: 'Food Not Bombs at Big Idea Bookstore',
    group: 'nearby',
    lat: 40.4603,
    lng: -79.94682,
    precision: 'address',
    who: 'Open to the public, no requirements listed',
    address: '4812 Liberty Avenue, Pittsburgh, PA 15224',
    hours: ['Listed as alternating Saturdays, 11 a.m. to 2 p.m.'],
    notes: 'A volunteer meal. From a local list with no update date, so confirm before you go.',
    contact: null,
    source: { label: 'Pitt, Pittsburgh-area food distributions', href: 'https://www.cec.pitt.edu/news/pittsburgh-area-food-drives-and-distributions' },
    confirmed: false,
  },
  {
    id: 'valleyview',
    name: 'Valley View Food Pantry',
    group: 'nearby',
    lat: 40.47078,
    lng: -79.9328,
    precision: 'address',
    who: 'Open to the public, no requirements listed',
    address: '601 N. Aiken Avenue, Pittsburgh, PA 15206',
    hours: ['Listed as the first Friday of each month, 11 a.m. to 2:30 p.m.'],
    notes: 'From a local list with no update date, so confirm before you go.',
    contact: null,
    source: { label: 'Pitt, Pittsburgh-area food distributions', href: 'https://www.cec.pitt.edu/news/pittsburgh-area-food-drives-and-distributions' },
    confirmed: false,
  },
  {
    id: 'jfcs',
    name: 'JFCS Squirrel Hill Food Pantry',
    group: 'nearby',
    lat: 40.41958,
    lng: -79.92792,
    precision: 'address',
    who: 'Reported: households that meet income guidelines in the 15217 ZIP code',
    address: '828 Hazelwood Avenue, Pittsburgh, PA 15217',
    hours: ['Reported: weekday mornings, with some appointment-only times', 'Call for the current schedule'],
    notes: 'It may not serve you if you live outside that ZIP code, so call first. Kosher food is available.',
    contact: { label: '412-421-2708', href: 'tel:+14124212708' },
    source: { label: 'JFCS of Pittsburgh', href: 'https://www.jfcspgh.org/services/squirrel-hill-food-pantry/' },
    confirmed: false,
  },
];

export const MORE_HELP = [
  { label: 'Greater Pittsburgh Community Food Bank: find food by ZIP code', href: 'https://pittsburghfoodbank.org' },
  { label: 'Dial 2-1-1 (United Way) for food and other local help', href: 'tel:211' },
];
